// Generates the SQL that seeds Supabase's `shop_item` table from the single
// source of truth, lib/data/shop_catalog.dart.
//
// The catalogue is built at runtime (50 styles x 10 colour variants + seed +
// prestige), so it can't be hand-maintained in SQL — regenerate instead:
//
//   dart run tool/seed_shop_items.dart > supabase/seed_shop_items.sql
//
// Then paste that file into the Supabase SQL Editor (or `psql -f`). Re-running
// is safe: it upserts. Run it again whenever the catalogue changes, or the
// server-side purchase_item() will price against a stale shelf.

import 'package:step_quest/data/shop_catalog.dart';

String _sqlQuote(String s) => "'${s.replaceAll("'", "''")}'";

void main() {
  final b = StringBuffer()
    ..writeln('-- GENERATED by tool/seed_shop_items.dart — do not edit by hand.')
    ..writeln('-- Regenerate after any change to lib/data/shop_catalog.dart.')
    ..writeln('-- Source of truth for prices used by purchase_item().')
    ..writeln()
    ..writeln('insert into shop_item '
        '(id, name, slot, rarity, price_tier, price_amount, in_shop) values');

  final rows = <String>[];
  for (final i in kShopCatalog) {
    // in_shop carries through so purchase_item() refuses reward-only loot —
    // several of those are priced 0 and would otherwise be free to "buy".
    rows.add('  (${_sqlQuote(i.id)}, ${_sqlQuote(i.name)}, '
        '${_sqlQuote(i.slot.name)}, ${_sqlQuote(i.rarity.name)}, '
        '${_sqlQuote(i.priceTier)}, ${i.priceAmount}, ${i.inShop})');
  }
  b.writeln(rows.join(',\n'));

  // Upsert so re-seeding a live shelf updates prices instead of failing.
  b
    ..writeln('on conflict (id) do update set')
    ..writeln('  name = excluded.name,')
    ..writeln('  slot = excluded.slot,')
    ..writeln('  rarity = excluded.rarity,')
    ..writeln('  price_tier = excluded.price_tier,')
    ..writeln('  price_amount = excluded.price_amount,')
    ..writeln('  in_shop = excluded.in_shop;')
    ..writeln()
    ..writeln('-- ${kShopCatalog.length} items seeded.');

  // ignore: avoid_print — this script's whole job is to print SQL to stdout.
  print(b.toString());
}
